# Generated by Django 5.0.6 on 2024-06-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_productosssss'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosssss',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
