# Generated by Django 5.0.6 on 2024-06-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_productosssss_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosssss',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
